GET http://localhost:3000

### Send fetch task REQUEST
GET http://localhost:3000/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwic3ViIjo5LCJpYXQiOjE3NDAwNjAyNjIsImV4cCI6MTc0MDE0NjY2Mn0.ZnkouId8CNeNKRPfygH_i8jY5yL_9dh_12anEvHAScA

### Send fetch task REQUEST
GET http://localhost:3000/tasks/
    ?page=1
    &limit=100
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwic3ViIjo5LCJpYXQiOjE3NDAwNjAyNjIsImV4cCI6MTc0MDE0NjY2Mn0.ZnkouId8CNeNKRPfygH_i8jY5yL_9dh_12anEvHAScA

### Find task REQUEST
GET http://localhost:3000/tasks/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwic3ViIjo5LCJpYXQiOjE3NDAwNjAyNjIsImV4cCI6MTc0MDE0NjY2Mn0.ZnkouId8CNeNKRPfygH_i8jY5yL_9dh_12anEvHAScA

### Create new task REQUEST
POST http://localhost:3000/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwic3ViIjo5LCJpYXQiOjE3NDAwNjAyNjIsImV4cCI6MTc0MDE0NjY2Mn0.ZnkouId8CNeNKRPfygH_i8jY5yL_9dh_12anEvHAScA
Content-Type: application/json

{
    "title": "title",  
    "description": "description",
    "status": "todo"
}

### Update task REQUEST
PUT http://localhost:3000/tasks/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwic3ViIjo5LCJpYXQiOjE3NDAwNjAyNjIsImV4cCI6MTc0MDE0NjY2Mn0.ZnkouId8CNeNKRPfygH_i8jY5yL_9dh_12anEvHAScA
Content-Type: application/json

{
    "project_id": 1,
    "status": "in-progress"
}

### Delete task REQUEST
DELETE http://localhost:3000/tasks/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwic3ViIjo5LCJpYXQiOjE3NDAwNjAyNjIsImV4cCI6MTc0MDE0NjY2Mn0.ZnkouId8CNeNKRPfygH_i8jY5yL_9dh_12anEvHAScA

### Send fetch projects REQUEST
GET http://localhost:3000/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwic3ViIjoxLCJpYXQiOjE3NDAwNjM0NjEsImV4cCI6MTc0MDE0OTg2MX0.IJOZn1PZq71jOPeHg05hp7kND5gUOa8O2hFGL3LEXvg

### Find projects REQUEST
GET http://localhost:3000/projects/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwic3ViIjo5LCJpYXQiOjE3NDAwNjAyNjIsImV4cCI6MTc0MDE0NjY2Mn0.ZnkouId8CNeNKRPfygH_i8jY5yL_9dh_12anEvHAScA

### Create new projects REQUEST
POST http://localhost:3000/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwic3ViIjo5LCJpYXQiOjE3NDAwNjAyNjIsImV4cCI6MTc0MDE0NjY2Mn0.ZnkouId8CNeNKRPfygH_i8jY5yL_9dh_12anEvHAScA
Content-Type: application/json

{
    "title": "title",  
    "description": "description"
}


### Signup User
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "john@gmail.com",
    "password": "123456",
    "firstName": "john",  
    "lastName": "doe"
}

### Login User
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "john@gmail.com",
    "password": "123456"
}

### Profile
GET http://localhost:3000/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwic3ViIjoxLCJpYXQiOjE3NDAwNjM0NjEsImV4cCI6MTc0MDE0OTg2MX0.IJOZn1PZq71jOPeHg05hp7kND5gUOa8O2hFGL3LEXvg
