GET http://localhost:3000

### Send fetch TASK REQUEST
GET http://localhost:3000/tasks

### Send fetch TASK REQUEST
GET http://localhost:3000/tasks/
    ?page=1
    &limit=100

### Find TASK REQUEST
GET http://localhost:3000/tasks/1

### Create New TASK REQUEST
POST http://localhost:3000/tasks
Content-Type: application/json

{
    "title": "title",  
    "description": "description",
    "status": "todo"
}

### Update TASK REQUEST
PUT http://localhost:3000/tasks/1
Content-Type: application/json

{
    "project_id": 1,
    "status": "in-progress"
}

### Delete TASK REQUEST
DELETE http://localhost:3000/task/1

### Create New PROJECT REQUEST
POST http://localhost:3000/projects
Content-Type: application/json

{
    "title": "title",  
    "description": "description"
}