GET http://localhost:3000

### Send fetch TASKS REQUEST
GET http://localhost:3000/tasks/?page=1&limit=2

### Find TASKS REQUEST
GET http://localhost:3000/tasks/1

### Create New TASKS REQUEST
POST http://localhost:3000/tasks
Content-Type: application/json
{
    "uuid": "uuid",
    "title": "title",  
    "description": "description",
    "status": "todo"
}

### Update TASKS REQUEST
PUT http://localhost:3000/tasks/2
Content-Type: application/json
{
    "status": "in-progress"
}

### Delete TASKS REQUEST
DELETE http://localhost:3000/tasks/1